import {firebaseConfig} from './shared-config.mjs?v=rp47';
import {teams} from './teams.mjs?v=rp47';
const $=s=>document.querySelector(s), params=new URLSearchParams(location.search);
const sessionToken=params.get('session')||'', teamOnly=params.get('team')||'', requestedFacility=(params.get('facility')||'barn').toLowerCase(), locationId=['barn','shed'].includes(requestedFacility)?requestedFacility:'barn';
const stableURL=()=>{const u=new URL(location.href);u.search='?checkin=1&facility='+encodeURIComponent(locationId)+(teamOnly?'&team='+encodeURIComponent(teamOnly):'');u.hash='';return u.href};
let sessions=[], selectedTime='', selectedPlayer=null, submitting=false;
const today=()=>{const d=new Date();return d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0')};
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const label=t=>{const [h,m]=t.split(':').map(Number);return new Date(2000,0,1,h,m).toLocaleTimeString([],{hour:'numeric',minute:'2-digit'})};
const digest=async v=>{const bytes=new TextEncoder().encode(v),hash=await crypto.subtle.digest('SHA-256',bytes);return [...new Uint8Array(hash)].map(b=>b.toString(16).padStart(2,'0')).join('')};
let svc;
async function services(){if(!svc)svc=(async()=>{const root='https://www.gstatic.com/firebasejs/12.19.0/';const [app,F]=await Promise.all(['app','firestore'].map(x=>import(root+'firebase-'+x+'.js')));return {F,db:F.getFirestore(app.initializeApp(firebaseConfig,'RebelsPrepCheckin'))}})();return svc}
function shell(x){$('#app').innerHTML='<div class="checkin-wrap">'+x+'</div>'}
function card(title,body){shell('<section class="checkin-card"><h1>'+esc(title)+'</h1>'+body+'</section>')}
async function load(){const {F,db}=await services();try{if(requestedFacility!==locationId)throw Error('Unknown facility');let tokens=[];if(/^[a-f0-9]{64}$/.test(sessionToken)){tokens=[sessionToken]}else if(locationId==='barn'||locationId==='shed'){const loc=await F.getDoc(F.doc(db,'rpCheckinLocations',locationId));if(loc.exists())tokens=(loc.data().sessions||[]).filter(x=>x.date===today()).map(x=>x.checkinToken).filter(Boolean)}tokens=[...new Set(tokens.filter(t=>/^[a-f0-9]{64}$/.test(t)))];const docs=await Promise.all(tokens.map(t=>F.getDoc(F.doc(db,'rpCheckinSessions',t))));sessions=docs.map((snap,i)=>{if(!snap.exists())return null;const d=snap.data();return {sessionToken:tokens[i],teamId:d.teamId,teamIds:d.teamIds||[d.teamId],clockToken:d.clockToken,date:d.date,active:d.active!==false,plan:{start:d.start,facility:d.facility,players:d.players||[]}}}).filter(s=>s&&s.date===today()&&s.active&&s.plan.facility===locationId&&(!teamOnly||s.teamIds.includes(teamOnly)));const unique=new Map();for(const s of sessions)unique.set(s.sessionToken,s);sessions=[...unique.values()]}catch{sessions=[]}}
function times(){selectedTime='';const a=[...new Set(sessions.map(s=>s.plan.start))].sort();if(!a.length){card('No practice found','<p>There is not an active practice available for check-in right now.</p><button id="retry">Try Again</button>');$('#retry').onclick=()=>location.reload();return}card('What time are you here for?','<p>Tap the start time you were given.</p><div class="checkin-options">'+a.map(t=>'<button data-time="'+t+'">'+label(t)+'</button>').join('')+'</div>');document.querySelectorAll('[data-time]').forEach(b=>b.onclick=()=>{selectedTime=b.dataset.time;players()})}
function list(){const m=new Map();sessions.filter(s=>s.plan.start===selectedTime).forEach(s=>(s.plan.players||[]).filter(p=>p&&p.id&&typeof p.name==='string'&&p.name.trim()).forEach(p=>{const key=String(p.id);const existing=m.get(key);if(!existing)m.set(key,{...p,sessionToken:s.sessionToken,sessionTokens:[s.sessionToken],clockToken:s.clockToken,clockTokens:[s.clockToken],teamId:s.teamId,teamIds:s.teamIds});else{existing.sessionTokens=[...new Set([...existing.sessionTokens,s.sessionToken])];existing.clockTokens=[...new Set([...existing.clockTokens,s.clockToken])];existing.teamIds=[...new Set([...(existing.teamIds||[]),...s.teamIds])]}}));return [...m.values()].sort((a,b)=>a.name.localeCompare(b.name))}
function players(){const a=list(),saved=(()=>{try{return JSON.parse(localStorage.getItem('RebelsPrep:checkin-player')||'null')}catch{return null}})();const savedPlayer=saved&&a.find(p=>p.id===saved.id&&(!saved.teamId||(p.teamIds||[p.teamId]).includes(saved.teamId))),quick=savedPlayer?'<button class="checkin-primary" id="quick">Check in as '+esc(savedPlayer.name)+'</button><p class="muted">Not you? Choose your name below.</p>':'';card('Find your name','<button id="back">‹ Back</button><p><strong>'+label(selectedTime)+'</strong></p>'+quick+'<div class="checkin-names">'+a.map(p=>'<button data-player="'+esc(p.id)+'">'+esc(p.name)+'</button>').join('')+'</div><button class="checkin-missing" id="missing">I’m not on the list</button>');$('#back').onclick=times;if($('#quick'))$('#quick').onclick=()=>{selectedPlayer=savedPlayer;confirmPlayer()};document.querySelectorAll('[data-player]').forEach(b=>b.onclick=()=>{selectedPlayer=a.find(p=>String(p.id)===b.dataset.player);confirmPlayer()});$('#missing').onclick=guest}
function confirmPlayer(){if(!selectedPlayer){players();return}card('Are you '+selectedPlayer.name+'?','<div class="checkin-options"><button id="no">No, go back</button><button class="checkin-primary" id="yes">Yes, that’s me</button></div>');$('#no').onclick=players;$('#yes').onclick=checkin}
async function checkin(){if(submitting)return;submitting=true;try{const {F,db}=await services(),id=await digest('player|'+selectedPlayer.sessionToken+'|'+selectedPlayer.id);await F.setDoc(F.doc(db,'rpCheckins',id),{kind:'player',playerId:selectedPlayer.id,name:selectedPlayer.name,sessionToken:selectedPlayer.sessionToken,clockToken:selectedPlayer.clockToken,teamId:selectedPlayer.teamId,teamIds:selectedPlayer.teamIds||[selectedPlayer.teamId],practiceTime:selectedTime,practiceDate:today(),facility:locationId,createdAt:F.serverTimestamp(),status:'checked-in'});localStorage.setItem('RebelsPrep:checkin-player',JSON.stringify({id:selectedPlayer.id,name:selectedPlayer.name,teamId:selectedPlayer.teamId}));history.replaceState(null,'',stableURL());card('You’re checked in','<p>'+esc(selectedPlayer.name)+' · '+label(selectedTime)+'</p><button id="undo">Wrong player? Undo</button><p><strong>Want faster check-in next time?</strong> On iPhone, tap Share, then Add to Home Screen. This shortcut will reopen the permanent '+esc(locationId==='barn'?'Barn':'facility')+' check-in page, not just today’s practice.</p>');$('#undo').onclick=async()=>{card('Tell your coach','<p>Your check-in was already sent. Tell your coach you selected the wrong player and they can correct it.</p>')}}catch{submitting=false;card('Check-in could not be saved','<p>Please tell your coach and try again.</p>')}}
function guest(){card('Not on the list?','<button id="back">‹ Back</button><p>Enter your name. Your coach must approve you before you are added.</p><label>Your name<input id="guest-name" autocomplete="name"></label><button class="checkin-primary" id="request">Ask to Join</button>');$('#back').onclick=players;$('#request').onclick=guestRequest}
async function guestRequest(){const name=$('#guest-name').value.trim();if(!name||name.length>100||submitting)return;submitting=true;try{const {F,db}=await services(),matches=sessions.filter(s=>s.plan.start===selectedTime);if(!matches.length)throw Error('No active practice');const primary=matches[0],sessionTokens=[...new Set(matches.map(s=>s.sessionToken))],clockTokens=[...new Set(matches.map(s=>s.clockToken))];const guestId=await digest('guest|'+primary.sessionToken+'|'+name.toLowerCase());await F.setDoc(F.doc(db,'rpCheckins',guestId),{kind:'guest-request',name,practiceTime:selectedTime,practiceDate:today(),facility:locationId,sessionToken:primary.sessionToken,sessionTokens,clockToken:primary.clockToken,clockTokens,createdAt:F.serverTimestamp(),status:'pending'});card('Request sent','<p>Tell the coach you are waiting for approval. You will join at the next block, not the block already in progress.</p>')}catch{submitting=false;card('Request could not be sent','<p>Please tell your coach you are here.</p>')}}
document.body.classList.add('checkin-mode');card('Loading check-in…','');await load();times();