// Independent snapshot; no runtime links to HotB.
export const drills = [
  {
    "name": "Basic Tee Work",
    "category": "Warm-Up",
    "primaryPurpose": "Prepare the body and reinforce adjustable posture and barrel path throughout the strike zone",
    "secondaryFocus": "Zone awareness and swing adjustability",
    "hittingMethod": "Tee",
    "equipment": "Tee & Net",
    "spaceSetup": "Hitting Nets",
    "howItWorks": "Work inside, outside, high and low tee positions",
    "coachingCues": "Move the tee around the zone and focus on how you should change your body and mechanics to accommodate different pitches.",
    "success": "Hard line-drive contact from gap to gap from all tee locations",
    "bestUsedFor": "Pre-practice warm-up; recalibrating posture and barrel path; preparing to cover the full zone",
    "mediaLink": "",
    "notes": "",
    "id": "drill-0",
    "kind": "drill",
    "tee": true,
    "tees": 1,
    "requiresCoach": false
  },
  {
    "name": "Skater Drill",
    "category": "Power",
    "primaryPurpose": "Maintain centered balance while moving pressure between the front and back sides",
    "secondaryFocus": "Prevent your weight from being too far forward or being up on your front foot",
    "hittingMethod": "Tee",
    "equipment": "Tee & Net",
    "spaceSetup": "Hitting Nets",
    "howItWorks": "Set up 6-10 inches back towards catcher with your feet together. Hop towards pitcher and land on front foot only, then hop towards catcher and land on back foot only, then hop forward again, hop to back foot, then stride into your full swing.",
    "coachingCues": "Keep your weight centered and balanced as you hop and into your stride / hit.",
    "success": "More powerful contact than a regular hit, should be center field line drives.",
    "bestUsedFor": "Drifting forward; getting onto the front foot early; weak contact caused by poor balance",
    "mediaLink": "",
    "notes": "",
    "id": "drill-1",
    "kind": "drill",
    "tee": true,
    "tees": 1,
    "requiresCoach": false
  },
  {
    "name": "Step In - Strong Stride",
    "category": "Power",
    "primaryPurpose": "Create a forceful, controlled forward move into the swing",
    "secondaryFocus": "Lower-half aggression and balance",
    "hittingMethod": "Tee",
    "equipment": "Tee & Net",
    "spaceSetup": "Hitting Nets",
    "howItWorks": "Set stance, take one large step back away from the plate. Set up, step in to normal spot with your back foot, take large aggressive stride forward with your front foot, and hit.",
    "coachingCues": "Keep your weight centered and balanced as you stride / hit.",
    "success": "More powerful contact than a regular hit, should be center field line drives.",
    "bestUsedFor": "Passive stride; weak contact; hitter needs a stronger forward move",
    "mediaLink": "",
    "notes": "",
    "id": "drill-2",
    "kind": "drill",
    "tee": true,
    "tees": 1,
    "requiresCoach": false
  },
  {
    "name": "Step Up/In - Strong Stride",
    "category": "Power",
    "primaryPurpose": "Build momentum into a strong stride without losing posture or balance",
    "secondaryFocus": "Lower-half sequencing and aggression",
    "hittingMethod": "Tee",
    "equipment": "Tee & Net",
    "spaceSetup": "Hitting Nets",
    "howItWorks": "Set stance, take one large step back away from the plate and one large step back towards the catcher. Set up, step up and in with your back foot into it's normal spot, then take large aggressive stride forward with your front foot, and hit.",
    "coachingCues": "Keep your weight centered and balanced as you stride / hit.",
    "success": "More powerful contact than a regular hit, should be center field line drives.",
    "bestUsedFor": "Weak forward move; limited lower-half momentum; weak contact",
    "mediaLink": "",
    "notes": "",
    "id": "drill-3",
    "kind": "drill",
    "tee": true,
    "tees": 1,
    "requiresCoach": false
  },
  {
    "name": "Ball on Shoulder",
    "category": "Contact / Barrel Control",
    "primaryPurpose": "Keep the hands and barrel from dropping during the load",
    "secondaryFocus": "Calm hands",
    "hittingMethod": "Tee",
    "equipment": "Tee & Net",
    "spaceSetup": "Hitting Nets",
    "howItWorks": "Set stance, place a softball on your back shoulder (where you bat would normally rest), set your bat on top of the ball, so the bat and your shoulder are holding the ball in place. Go into your swing, only eliminate your separation and go from load to the beginning of your swing without the ball falling off your shoulder. Then release the bat / swing and hit ball. The ball should fall forward towards the plate.",
    "coachingCues": "Keep your hands / bat calm. Stay set and centered during your load. Keeps your hands from dropping when you go into your load.",
    "success": "Line drives. No pop flies.",
    "bestUsedFor": "Pop-ups; frequent foul balls; hands dropping during the load; contact under the ball",
    "mediaLink": "",
    "notes": "",
    "id": "drill-4",
    "kind": "drill",
    "tee": true,
    "tees": 1,
    "requiresCoach": false
  },
  {
    "name": "2Tee - Front/Back",
    "category": "Contact / Barrel Control",
    "primaryPurpose": "Keep the barrel above the rear ball and enter the hitting zone on a level path",
    "secondaryFocus": "Level Barrel Head",
    "hittingMethod": "Tee",
    "equipment": "Two Tees, Net",
    "spaceSetup": "Hitting Nets",
    "howItWorks": "Set up a single tee in normal spot. Set second tee about 12-inches behind the first tee and set the ball about 6-inches lower than the first tee. Swing and hit the front tee without touching the back ball on the back tee.",
    "coachingCues": "Keep your hands from dropping by not hitting the back ball.",
    "success": "Line drives. No pop flies.",
    "bestUsedFor": "Pop-ups; dropped hands; steep down-up swing; contact under the ball",
    "mediaLink": "",
    "notes": "",
    "id": "drill-5",
    "kind": "drill",
    "tee": true,
    "tees": 2,
    "requiresCoach": false
  },
  {
    "name": "2Tee - Inside/Outside",
    "category": "Vision / Pitch Recognition",
    "primaryPurpose": "Recognize pitch location late and adjust the swing path without pausing",
    "secondaryFocus": "Inside / Outside Pitches",
    "hittingMethod": "Tee",
    "equipment": "Two Tees, Net",
    "spaceSetup": "Hitting Nets",
    "howItWorks": "Set up a tee as a low inside pitch (make sure it's moved up in zone) and the second tee as a high outside pitch (move tee back so it's centered on your stance). As one girl loads and starts to engage her swing, her partner says \"inside\" or \"outside, and the girl at the plate has to hit what she calls.  As it progresses, wait later in the swing to  call the pitch.",
    "coachingCues": "Keep your hands in tight to start, the start of the swing should be the same and alter only after you know what your going after.",
    "success": "One smooth motion when hitting either pitch and consistent contact. Don't pause or studder.",
    "bestUsedFor": "Slow pitch-location decisions; difficulty covering inside and outside pitches; one-swing-only pattern",
    "mediaLink": "",
    "notes": "",
    "id": "drill-6",
    "kind": "drill",
    "tee": true,
    "tees": 2,
    "requiresCoach": false
  },
  {
    "name": "Speed Side Toss",
    "category": "Vision / Pitch Recognition",
    "primaryPurpose": "Make rapid swing-path adjustments to changing pitch locations",
    "secondaryFocus": "Eye Hand coordination",
    "hittingMethod": "Side Toss",
    "equipment": "Net",
    "spaceSetup": "Hitting Nets",
    "howItWorks": "Set up to hit, second person sets up to side toss. Toss as quickly as you can for as long as the person can last.  Hit every pitch they throw while changing your swing and body mechanics to compensate for the  pitch location.",
    "coachingCues": "Swing all the way through, be quick back to reset. Change your swing and body to get to the ball for good contact.",
    "success": "Good eye-hand coordination with good consistent contact for every ball in all the zones.",
    "bestUsedFor": "Slow visual decisions; poor eye-hand coordination; difficulty adjusting to unexpected pitch locations",
    "mediaLink": "",
    "notes": "",
    "id": "drill-7",
    "kind": "drill",
    "tee": false,
    "tees": 0,
    "requiresCoach": false
  },
  {
    "name": "Regular Side Toss",
    "category": "Vision / Pitch Recognition",
    "primaryPurpose": "Adjust posture and barrel path to pitches throughout the strike zone",
    "secondaryFocus": "Eye Hand coordination",
    "hittingMethod": "Side Toss",
    "equipment": "Net",
    "spaceSetup": "Hitting Nets",
    "howItWorks": "Tosser gives a variety of pitches, In, Out, High, Low. Variety, add an 0-2 count, so they have to swing for contact. Change swing and body mechanics to compensate for the  pitch location.",
    "coachingCues": "There are a variety of cues depending on what they are doing. Look for consistent hard contact from gap to gap.",
    "success": "Good eye-hand coordination with good consistent contact for every ball in all the zones.",
    "bestUsedFor": "Poor zone coverage; one-swing-only pattern; two-strike contact; inconsistent contact by pitch location",
    "mediaLink": "",
    "notes": "",
    "id": "drill-8",
    "kind": "drill",
    "tee": false,
    "tees": 0,
    "requiresCoach": false
  },
  {
    "name": "Pitch Behind",
    "category": "Timing",
    "primaryPurpose": "Delay commitment while staying ready to accelerate through contact",
    "secondaryFocus": "Contact point and late adjustability",
    "hittingMethod": "Rear Toss",
    "equipment": "Net (no plate required)",
    "spaceSetup": "Hitting Nets",
    "howItWorks": "Set up to hit, second person sets up behind person by 8 feet and tosses the ball thru the strike zone (aim a little outside to start with). Hitter has to wait on ball to travel thru zone to front part of plate and explode to contact.",
    "coachingCues": "Wait for the ball to travel to the front part of the plate. Swing fast and drive it straight ahead.",
    "success": "The more CF the ball travels the better. This shows too early, too late really well.",
    "bestUsedFor": "Early commitment; lunging; difficulty letting the ball travel; weak contact on off-speed pitches",
    "mediaLink": "",
    "notes": "",
    "id": "drill-9",
    "kind": "drill",
    "tee": false,
    "tees": 0,
    "requiresCoach": false
  },
  {
    "name": "Plate Recognition",
    "category": "Vision / Pitch Recognition",
    "primaryPurpose": "Identify ball/strike status and pitch location early enough to make a quality swing decision",
    "secondaryFocus": "Picking a pitch you can Drive",
    "hittingMethod": "Front Toss",
    "equipment": "Tee, Striped Colored Plate",
    "spaceSetup": "Hitting Nets",
    "howItWorks": "Set up six balls across the plate from inside (1) to outside (6). Throw front toss and the hitter has to call out the number the pitch after she either lets it go, or swings.",
    "coachingCues": "Recognize location early; take pitches outside the target zone; attack pitches that can be driven",
    "success": "Correct ball/strike and location calls followed by hard contact on selected pitches",
    "bestUsedFor": "Chasing outside the zone; taking hittable pitches; poor pitch-location recognition; weak swing decisions",
    "mediaLink": "",
    "notes": "",
    "id": "drill-10",
    "kind": "front",
    "tee": true,
    "tees": 1,
    "requiresCoach": true
  },
  {
    "name": "Front Toss",
    "category": "Vision / Pitch Recognition",
    "primaryPurpose": "Transfer mechanical adjustments into timing and hard contact against a moving ball",
    "secondaryFocus": "Pitch recognition and gap-to-gap contact",
    "hittingMethod": "Front Toss",
    "equipment": "L-screen, balls, plate",
    "spaceSetup": "Tunnel",
    "howItWorks": "Set up a screen and pitch to hitter.",
    "coachingCues": "There are a variety of cues depending on what they are doing. Look for consistent hard contact from gap to gap.",
    "success": "Good eye-hand coordination with good consistent contact for every ball in all the zones.",
    "bestUsedFor": "Testing whether tee-work adjustments transfer to a moving ball; general timing; contact quality",
    "mediaLink": "",
    "notes": "",
    "id": "drill-11",
    "kind": "front",
    "tee": false,
    "tees": 0,
    "requiresCoach": true
  },
  {
    "name": "Front Toss / 1 Tee Change",
    "category": "Timing",
    "primaryPurpose": "Stay loaded and adjust timing when the pitch may be a changeup",
    "secondaryFocus": "Keeping your load ready for a fast or changeup.",
    "hittingMethod": "Front Toss",
    "equipment": "Hitting Tunnel and Tee",
    "spaceSetup": "Tunnel",
    "howItWorks": "Set up a tee as an outside pitch. Throw front toss, only randomly alternate when you actually throw the pitch. When you don't throw, the hitter has to continue her swing and hit the outside tee (signifying her waiting on a changeup.",
    "coachingCues": "Be smooth, the pause should look easy. Keep your weight back, especially when you have to wait to hit the changeup.",
    "success": "Hitting pitched balls and the ball off the tee like you knew it was coming.",
    "bestUsedFor": "Early commitment on changeups; drifting forward; inability to maintain the load on off-speed pitches",
    "mediaLink": "",
    "notes": "",
    "id": "drill-12",
    "kind": "front",
    "tee": true,
    "tees": 1,
    "requiresCoach": true
  },
  {
    "name": "Cross Over - Strong Stride",
    "category": "Power",
    "primaryPurpose": "Feel weight transfer into a long, forceful stride while keeping the hands back",
    "secondaryFocus": "Lower-half power and sequencing",
    "hittingMethod": "Tee",
    "equipment": "Tee & Net",
    "spaceSetup": "Hitting Nets",
    "howItWorks": "Set up 6-8 inches back towards the catcher with your feet together. Take your front foot and place it on the other side of your back foot (it look like you have to pee). Lean forward with your hip only as far as you can, then go into a long stride and hit.",
    "coachingCues": "Keep you hands back, lean with your hip, and take a long stride.",
    "success": "Really hard hit balls.",
    "bestUsedFor": "Weak contact; limited lower-half contribution; hitter does not feel weight transfer",
    "mediaLink": "",
    "notes": "",
    "id": "drill-13",
    "kind": "drill",
    "tee": true,
    "tees": 1,
    "requiresCoach": false
  },
  {
    "name": "Machine Pitch",
    "category": "Vision / Pitch Recognition",
    "primaryPurpose": "Adjust to game-speed velocity, pitch location, and changing counts",
    "secondaryFocus": "Pitch-type recognition and consistent contact",
    "hittingMethod": "Machine",
    "equipment": "Pitching machine, balls, tunnel",
    "spaceSetup": "Tunnel with pitching machine",
    "howItWorks": "Use the machine at game-like speeds and locations. Mix locations, pitch types, and counts while the hitter works on recognition and hard contact.",
    "coachingCues": "Track the ball early; be on time; adjust posture to location; maintain the planned approach for the count",
    "success": "On-time hard contact on game-speed pitches in the intended part of the field",
    "bestUsedFor": "Late against velocity; difficulty adjusting to location; inconsistent contact at game speed",
    "mediaLink": "",
    "notes": "",
    "id": "drill-14",
    "kind": "machine",
    "tee": false,
    "tees": 0,
    "requiresCoach": false
  },
  {
    "name": "Small Ball Machine",
    "category": "Contact / Barrel Control",
    "primaryPurpose": "Improve precise barrel-to-ball contact using a smaller ball and bat",
    "secondaryFocus": "Eye Hand coordination",
    "hittingMethod": "Other",
    "equipment": "Small Ball Machine, Thin Bat, Wiffle Balls",
    "spaceSetup": "Open Space",
    "howItWorks": "Same as machine pitch only use a thin bat and it pitches really small wiffle balls.",
    "coachingCues": "Keep your eye on the ball, don't pull off, stay in the zone and focus on contact",
    "success": "Frequent centered contact with the small ball",
    "bestUsedFor": "Swing-and-miss problems; poor barrel accuracy; difficulty tracking a smaller target",
    "mediaLink": "",
    "notes": "",
    "id": "drill-15",
    "kind": "drill",
    "tee": false,
    "tees": 0,
    "requiresCoach": false
  },
  {
    "name": "One Leg Bucket Sits",
    "category": "Power",
    "primaryPurpose": "Generate force from the back leg before striding into the swing",
    "secondaryFocus": "Lower-half mechanics",
    "hittingMethod": "Tee",
    "equipment": "Tee and Bucket",
    "spaceSetup": "Hitting Nets",
    "howItWorks": "Set up about 4-5 inches towards catcher. Put a bucket under your back leg, so you can sit down. Lift your front leg a couple inches off the ground. Lift yourself up using your back leg only, then stride and hit.",
    "coachingCues": "Feel the push off your back foot. Drive hard, hit hard",
    "success": "Really hard hit balls.",
    "bestUsedFor": "Weak back-side drive; poor lower-half contribution; weak contact",
    "mediaLink": "",
    "notes": "",
    "id": "drill-16",
    "kind": "drill",
    "tee": true,
    "tees": 1,
    "requiresCoach": false
  },
  {
    "name": "Tire",
    "category": "Contact / Barrel Control",
    "primaryPurpose": "Keep the barrel level through the hitting zone without dropping the hands",
    "secondaryFocus": "Eliminating the down/up swing.",
    "hittingMethod": "Other",
    "equipment": "Tire & Net",
    "spaceSetup": "Hitting Nets",
    "howItWorks": "Use a short bucket and set a tire upright on top. Set a ball on top of the tire and hit it off without hitting the tire.",
    "coachingCues": "Stay level through the zone. Keep your hands up.",
    "success": "Clean hits without hitting the tire.",
    "bestUsedFor": "Down-up swing; dropping hands; pop-ups; contact under the ball",
    "mediaLink": "",
    "notes": "",
    "id": "drill-17",
    "kind": "drill",
    "tee": false,
    "tees": 0,
    "requiresCoach": false
  },
  {
    "name": "Angle Hitting",
    "category": "Contact / Barrel Control",
    "primaryPurpose": "Enter the hitting zone early and keep the barrel on plane through contact",
    "secondaryFocus": "Late contact / foul balls; Early contact / pulling foul",
    "hittingMethod": "Tee",
    "equipment": "Tee & Net",
    "spaceSetup": "Hitting Nets",
    "howItWorks": "Set up like normal. Then turn your feet so your feet (toe to toe) line up to 3rd base line. Then switch to line up with 1st base line.",
    "coachingCues": "Get on line quickly, stay level through the zone.",
    "success": "Try and hit the ball gap to gap.",
    "bestUsedFor": "Short time on plane; difficulty covering off-speed pitches; weak gap-to-gap contact",
    "mediaLink": "",
    "notes": "",
    "id": "drill-18",
    "kind": "drill",
    "tee": true,
    "tees": 1,
    "requiresCoach": false
  },
  {
    "name": "Surf Board",
    "category": "Contact / Barrel Control",
    "primaryPurpose": "Keep the barrel level through the hitting zone without a down-up path",
    "secondaryFocus": "Eliminating the down/up swing.",
    "hittingMethod": "Tee",
    "equipment": "Surf Board",
    "spaceSetup": "Hitting Nets",
    "howItWorks": "Set up the surf board and hit. Try not to hit the surf board.",
    "coachingCues": "Stay level through the zone. Keep your hands up.",
    "success": "Clean hits without hitting the surf board.",
    "bestUsedFor": "Down-up swing; dropping hands; pop-ups; contact under the ball",
    "mediaLink": "",
    "notes": "",
    "id": "drill-19",
    "kind": "drill",
    "tee": true,
    "tees": 0,
    "requiresCoach": false
  },
  {
    "name": "Hitting Bag",
    "category": "Power",
    "primaryPurpose": "Increase intent, bat speed, and force through contact",
    "secondaryFocus": "Power",
    "hittingMethod": "Other",
    "equipment": "Hitting Dummy",
    "spaceSetup": "Open Space",
    "howItWorks": "Hit the dummy as hard as you can. 10x as hard as you can. 10x as hard AND as fast as you can.  5x as hard as you can High, Middle, and Low.",
    "coachingCues": "Swing harder, swing faster.",
    "success": "Loud, forceful contact with consistent intent at high, middle, and low targets",
    "bestUsedFor": "Low swing intent; low bat speed; weak contact; hitter needs to learn maximum-effort swings",
    "mediaLink": "",
    "notes": "",
    "id": "drill-20",
    "kind": "drill",
    "tee": false,
    "tees": 0,
    "requiresCoach": false
  },
  {
    "name": "Knob to Ball",
    "category": "Contact / Barrel Control",
    "primaryPurpose": "Improve hand-path accuracy by directing the knob to the ball",
    "secondaryFocus": "Taking your hands to the ball.",
    "hittingMethod": "Other",
    "equipment": "None",
    "spaceSetup": "Open Space",
    "howItWorks": "Set up, have partner toss balls into the zone about belly/chest high. Use knob of bat to pop the balls down.",
    "coachingCues": "Short motions, clean, and hit the knob to the ball hard.",
    "success": "Clean hits, bringing hands and bat back to reset.",
    "bestUsedFor": "Long hand path; poor hand accuracy; difficulty taking the hands directly to the ball",
    "mediaLink": "",
    "notes": "",
    "id": "drill-21",
    "kind": "drill",
    "tee": false,
    "tees": 0,
    "requiresCoach": false
  },
  {
    "name": "One Hand Bat",
    "category": "Contact / Barrel Control",
    "primaryPurpose": "Front hand not pulling away, Back hand pushing through.",
    "secondaryFocus": "Front hand not pulling away, Back hand pushing through.",
    "hittingMethod": "Tee",
    "equipment": "Short Bat, Tee & Net",
    "spaceSetup": "Hitting Nets",
    "howItWorks": "Set up tee, get down on back knee. Use front hand on short bad and practice hitting to extension with front hand only. Switch to backhand and hit ball off tee, keep front shoulder in the zone. Don't pull off.",
    "coachingCues": "Stay through the zone, keep your shoulder in the zone, don't pull off and away",
    "success": "Clean hits with your shoulders in the zone.",
    "bestUsedFor": "Shoulder and hand control hitting through the zone.",
    "mediaLink": "",
    "notes": "",
    "id": "drill-22",
    "kind": "drill",
    "tee": true,
    "tees": 1,
    "requiresCoach": false
  },
  {
    "name": "Extensions",
    "category": "Bat Path / Swing Plane",
    "primaryPurpose": "Keeping your front shoulder from opening by stopping your extension too far out and across your body",
    "secondaryFocus": "Getting your extension to be fully extended, both arms out, palm up/down, with a good bat whip/extension.",
    "hittingMethod": "Tee",
    "equipment": "Tee & Net",
    "spaceSetup": "Hitting Nets",
    "howItWorks": "Practice going to contact only. Then do the next set to extension. Get your extension to be more towards 2B as a righty, not SS/3B. Make sure your front elbow isn't fully bent (you're rotating your shoulders like machine) and activate more of a bat whip through the zone and fully out and extended.",
    "coachingCues": "Watch your front elbow/arm. Get fully extended. Don't rotate your top half in one motion. Get your bat into and through the zone and extended out.",
    "success": "Hard hit ball, good bat snap and strong directional bat extension.",
    "bestUsedFor": "Pulling the ball, not being able to hit an outside pitch, and rolling your hands over",
    "mediaLink": "",
    "notes": "",
    "id": "drill-23",
    "kind": "drill",
    "tee": true,
    "tees": 1,
    "requiresCoach": false
  },
  {
    "name": "Hunt Your Zone",
    "category": "Vision / Pitch Recognition",
    "primaryPurpose": "Attacking a selected zone.",
    "secondaryFocus": "Quicker decision making.",
    "hittingMethod": "Front Toss",
    "equipment": "Hitting Tunnel",
    "spaceSetup": "Hitting Tunnel",
    "howItWorks": "Before each round, the hitter chooses one specific area—for example, middle-in, middle-away, or belt-high. The hitter swings only when the pitch enters that area. Throw 8–10 pitches per round, hard swing at pitches in the selected zone, take everything else—even strikes, the hitter must call “yes” or “no” before the ball reaches the plate",
    "coachingCues": "It's a strike until it isn't. Load, separate, and get your front foot down before you release your hands.",
    "success": "Correct swing decisions, correct takes, and hard contact on selected pitches.",
    "bestUsedFor": "Attacking a selected zone.",
    "mediaLink": "",
    "notes": "",
    "id": "drill-24",
    "kind": "front",
    "tee": false,
    "tees": 0,
    "requiresCoach": true
  },
  {
    "name": "Damage or Take",
    "category": "Vision / Pitch Recognition",
    "primaryPurpose": "Teaching hitters to take strikes they cannot drive.",
    "secondaryFocus": "Hard hit balls.",
    "hittingMethod": "Front Toss",
    "equipment": "Hitting Tunnel",
    "spaceSetup": "Hitting Tunnel",
    "howItWorks": "The hitter swings only at pitches she believes she can hit hard. A pitch can be a strike and still be the correct pitch to take. Scoring: Hard contact: +2, Correct take on a poor pitch: +1, Weak contact: –1, Chase: –2, Take on a clearly hittable pitch: –1",
    "coachingCues": "Be patient and watch it out of the pitchers hand.",
    "success": "Hard hit line drives.",
    "bestUsedFor": "This teaches that “throwing the bat at a strike” is not the same as making a good decision.",
    "mediaLink": "",
    "notes": "",
    "id": "drill-25",
    "kind": "front",
    "tee": false,
    "tees": 0,
    "requiresCoach": true
  },
  {
    "name": "Deep Contact Tee",
    "category": "Vision / Pitch Recognition",
    "primaryPurpose": "Establishing the correct contact point for an outside pitch.",
    "secondaryFocus": "Staying closed, maintaining posture, and driving the ball to the opposite-field gap.",
    "hittingMethod": "Tee",
    "equipment": "Tee & Net",
    "spaceSetup": "Hitting Nets",
    "howItWorks": "Place the tee on the outer third of the plate and slightly deeper than the hitter’s normal middle-pitch contact point. The hitter drives the ball through the middle or opposite-field gap. Move the tee slightly up and down while keeping it on the outer third.",
    "coachingCues": "Let the ball travel, keep the front shoulder closed, stay inside the ball, drive through the opposite-field gap, do not reach—maintain your posture.",
    "success": "Firm line drives through the middle or opposite-field gap without slicing, rolling over, lunging, or pulling the ball weakly.",
    "bestUsedFor": "Hitters who pull off outside pitches, reach with their hands, roll over, or make contact too far in front.",
    "mediaLink": "",
    "notes": "",
    "id": "drill-26",
    "kind": "drill",
    "tee": true,
    "tees": 1,
    "requiresCoach": false
  },
  {
    "name": "Inside Contact",
    "category": "Vision / Pitch Recognition",
    "primaryPurpose": "Establishing the correct contact point for an inside pitch.",
    "secondaryFocus": "Staying closed, maintaining posture, and driving the ball to the same side gap.",
    "hittingMethod": "Tee",
    "equipment": "Tee & Net",
    "spaceSetup": "Hitting Nets",
    "howItWorks": "Place the tee on the inner third of the plate and out in front of your stance by a foot. The hitter drives the ball through the same side field and gap.",
    "coachingCues": "Turn your hips fast and first and catch the ball out front before it jams you.",
    "success": "Firm line drives through the same side field gap while staying in fair territory.",
    "bestUsedFor": "Driving inside pitches fair, or using it on a two strike pitch to foul off and survive.",
    "mediaLink": "",
    "notes": "",
    "id": "drill-27",
    "kind": "drill",
    "tee": true,
    "tees": 1,
    "requiresCoach": false
  },
  {
    "name": "Velocity Training",
    "category": "Vision / Pitch Recognition",
    "primaryPurpose": "Identify change ups versus fastballs",
    "secondaryFocus": "Stay loaded to hit a change, but still be able to hit a fastball",
    "hittingMethod": "Machine",
    "equipment": "Hitting Tunnel",
    "spaceSetup": "Hitting Tunnel",
    "howItWorks": "Set the machine to alternate randomly between a fastball and changeup.",
    "coachingCues": "Look for a fastball with the load and separation, while getting your front foot down so you can still hit a change before you release your hands",
    "success": "Good contact on fastballs and changeups",
    "bestUsedFor": "Identify change ups versus fastballs",
    "mediaLink": "",
    "notes": "",
    "id": "drill-28",
    "kind": "machine",
    "tee": false,
    "tees": 0,
    "requiresCoach": false
  },
  {
    "name": "Two Strike Approach",
    "category": "Two-Strike",
    "primaryPurpose": "Surviving when down in the count with a base hit.",
    "secondaryFocus": "Foul off balls you might get rung up on.",
    "hittingMethod": "Front Toss",
    "equipment": "Hitting Tunnel",
    "spaceSetup": "Hitting Tunnel",
    "howItWorks": "Give the hitter an 0-2 count and give a variety of pitches around the zone. If it's questionable, foul it off until you find something you can put in fair territory.",
    "coachingCues": "Choke up, scoot up to the plate. Look for contact, not for a homerun.",
    "success": "Fouling off crappy pitches and getting decent contact out or a corner pitch.",
    "bestUsedFor": "Surviving a pitchers count.",
    "mediaLink": "",
    "notes": "",
    "id": "drill-29",
    "kind": "front",
    "tee": false,
    "tees": 0,
    "requiresCoach": true
  },
  {
    "name": "Bucket Drops",
    "category": "Vision / Pitch Recognition",
    "primaryPurpose": "Learning to sit on a change up",
    "secondaryFocus": "Change ups",
    "hittingMethod": "Tee",
    "equipment": "Bucket with cushion top, Tee & Net",
    "spaceSetup": "Hitting Nets",
    "howItWorks": "Set up a bucket with a spring top where you would normally put a tee.  Set up a chair in the other strike zone and have someone drop a ball and have it bounce off the lid. Hitter strikes the ball after the ball bounces off the lid.",
    "coachingCues": "Wait for ball. Get your front foot down.",
    "success": "Good clean contact.",
    "bestUsedFor": "Hitting off speed pitches",
    "mediaLink": "",
    "notes": "",
    "id": "drill-30",
    "kind": "drill",
    "tee": true,
    "tees": 1,
    "requiresCoach": false
  },
  {
    "name": "2 Tennis Balls In/Out",
    "category": "Vision / Pitch Recognition",
    "primaryPurpose": "Eye hand coordination on finding an inside versus outside pitch",
    "secondaryFocus": "Quicker decision making.",
    "hittingMethod": "Front Toss",
    "equipment": "Tennis Balls &Hitting Tunnel",
    "spaceSetup": "Hitting Tunnel",
    "howItWorks": "Hold two tennis balls in one hand. Throw them both at the same time. As they are traveling, yell inside/outside, and hitter hits the one you call-out.  You can do this with different colored tennis balls too.",
    "coachingCues": "Watch the ball(s). Learn to stick with the decision you make, don't hesitate or wait.  See it and drive it.",
    "success": "Good clean contact on the correct ball.",
    "bestUsedFor": "Pitch recognition",
    "mediaLink": "",
    "notes": "",
    "id": "drill-31",
    "kind": "front",
    "tee": false,
    "tees": 0,
    "requiresCoach": true
  },
  {
    "name": "Bunting w/ Direction",
    "category": "Bunting / Slap",
    "primaryPurpose": "Laying down a direction bunt",
    "secondaryFocus": "Taking the pitch where you need to put a successful bunt down.",
    "hittingMethod": "Machine",
    "equipment": "Hitting Tunnel & Cones",
    "spaceSetup": "Hitting Tunnel",
    "howItWorks": "Set up cones down 1B and 3B line about 6-8 feet away. Ten pitches, count how many you get to stop before they go past the cones.",
    "coachingCues": "Don't stab at the ball, let it travel to you and cushion the bunt. Try to hit off the top 4-inches of the bat",
    "success": "Soft slow traveling bunts that does not go back to the pitcher.",
    "bestUsedFor": "Successful bunts",
    "mediaLink": "",
    "notes": "",
    "id": "drill-32",
    "kind": "machine",
    "tee": false,
    "tees": 0,
    "requiresCoach": false
  },
  {
    "name": "Bat to Hip Drill",
    "category": "Lower-Half Mechanics",
    "primaryPurpose": "Rotating (trailing) hip into swing",
    "secondaryFocus": "Rotating your foot to release your back hip.",
    "hittingMethod": "Tee",
    "equipment": "Tee & Net",
    "spaceSetup": "Hitting Nets",
    "howItWorks": "Set up a tee and set up so the tee is belt high and about 1 foot away. Set your bat across your belt horizontally (with the bat head facing the catcher). Rotate your hip, hard, and hit the ball of the tee.",
    "coachingCues": "Squash the bug with your back foot, push you hip through",
    "success": "Proper hip rotation.",
    "bestUsedFor": "Full rotation with you hip, releasing your back hip.",
    "mediaLink": "",
    "notes": "",
    "id": "drill-33",
    "kind": "drill",
    "tee": true,
    "tees": 1,
    "requiresCoach": false
  },
  {
    "name": "Stagger Drills",
    "category": "Contact / Barrel Control",
    "primaryPurpose": "Driving hits to opposite field.",
    "secondaryFocus": "Prevents opening your shoulder and hips.",
    "hittingMethod": "Tee",
    "equipment": "Tee & Net",
    "spaceSetup": "Hitting Nets",
    "howItWorks": "Set up tee (a little out front) and your normal stance. Move your back foot back towards the outside of the batters box (think of an \"open stance\" but with your back foot out, not your front). Keep your feet planted and hit the ball. It doesn’t have to be hard, but make it a full swing. You should feel it in your hip.",
    "coachingCues": "Stay closed at contact. Drive the ball to the opposite field.",
    "success": "Clean line drives to opposite field.",
    "bestUsedFor": "Pulling off the ball and not driving the ball to the opposite side of the field.",
    "mediaLink": "",
    "notes": "",
    "id": "drill-34",
    "kind": "drill",
    "tee": true,
    "tees": 1,
    "requiresCoach": false
  },
  {
    "name": "One Hand - Straight Arm",
    "category": "Contact / Barrel Control",
    "primaryPurpose": "Keeps your shoulder from flying out.",
    "secondaryFocus": "Back hand control and punching through the zone.",
    "hittingMethod": "Tee",
    "equipment": "Tee & Net",
    "spaceSetup": "Hitting Nets",
    "howItWorks": "Set up tee with a ball on it. Take your leading arm off the bat, and while hold a ball, fully extend your lead arm (while holding a ball) out above the tee. While holding your bat (you may need to choke up a little), swing and hit the ball on the tee without moving your front arm fully extended straight out at your partner.",
    "coachingCues": "Keep you arm straight out, don't move your front arm with your swing. Keep your shoulder in.",
    "success": "Good contact without your front arm moving or your front shoulder opening up.",
    "bestUsedFor": "Pulling off the ball.",
    "mediaLink": "",
    "notes": "",
    "id": "drill-35",
    "kind": "drill",
    "tee": true,
    "tees": 1,
    "requiresCoach": false
  },
  {
    "name": "One-Handed Catch",
    "category": "Bat Path / Swing Plane",
    "primaryPurpose": "Eye hand coordination.",
    "secondaryFocus": "Taking your hands/knob to the ball.",
    "hittingMethod": "Soft Toss",
    "equipment": "Open Space",
    "spaceSetup": "Open Space",
    "howItWorks": "Set up to hit without a bat. Have your partner stand 5-7 feet in front of you and toss you a ball (in and around the strike zone). Go into your swing (without a bat) and catch the ball with your front hand. Alternate and use your back hand.",
    "coachingCues": "Take your hands to the ball.",
    "success": "Staying balanced and catching the ball with either hand.",
    "bestUsedFor": "Taking your hands to the ball. Finding pitches in all strike zones.",
    "mediaLink": "",
    "notes": "",
    "id": "drill-36",
    "kind": "drill",
    "tee": false,
    "tees": 0,
    "requiresCoach": false
  },
  {
    "name": "Bunting Station",
    "category": "Bunting / Slap",
    "primaryPurpose": "Eye hand coordination.",
    "secondaryFocus": "Barrel control",
    "hittingMethod": "Other",
    "equipment": "Baseball Machine / Bat",
    "spaceSetup": "Open Space",
    "howItWorks": "Set up the green pitching machine as a bunt station. Use 43' as the distance. Use a barn bat, not your own.",
    "coachingCues": "Try to make contact on the end 4 inches of the bat to deaden the ball. Don't put it right back to the pitcher",
    "success": "Soft bunts going down 1B/3B line about 3-10 feet.",
    "bestUsedFor": "Bunting",
    "mediaLink": "",
    "notes": "",
    "id": "drill-37",
    "kind": "drill",
    "tee": false,
    "tees": 0,
    "requiresCoach": false
  },
  {
    "name": "RMT Station",
    "category": "Contact / Barrel Control",
    "primaryPurpose": "Building strength and control throughout your swing bath",
    "secondaryFocus": "Power",
    "hittingMethod": "Dry / No Ball",
    "equipment": "RMT Bats",
    "spaceSetup": "Open Space",
    "howItWorks": "Get the RMT Bats. Start with a low weight and with both hands on the bat, swing for a hit. Start at 25%, then 50%, then move to full. 10-15 per set. Then move up weight in the bat.",
    "coachingCues": "Do NOT drop your hands in your separation or through your swing path. Swing level through the zone. Imagine hitting a high pitch.",
    "success": "Strong swings while maintaining good mechanics.",
    "bestUsedFor": "Building strength while keeping good barrel control and a level head throughout the zone.",
    "mediaLink": "",
    "notes": "",
    "id": "drill-38",
    "kind": "drill",
    "tee": false,
    "tees": 0,
    "requiresCoach": false
  },
  {
    "name": "Med Ball Station",
    "category": "Power",
    "primaryPurpose": "Building strength and power.",
    "secondaryFocus": "Power",
    "hittingMethod": "Dry / No Ball",
    "equipment": "Medicine Balls",
    "spaceSetup": "Plyo Wall",
    "howItWorks": "Set up like your hitting, but hold a med ball in-place of the bat. Load, stride, and throw the ball into the plyo wall.  Do 10 reps, then move up in weight. You can also do a \"skater\" drill motion to lunge into the throw harder.",
    "coachingCues": "Do not throw from your hip. Keep your hands up. Use your entire body, starting with your legs.",
    "success": "Hard throws, using your core while keeping your hands up.",
    "bestUsedFor": "Building strength and power.",
    "mediaLink": "",
    "notes": "",
    "id": "drill-39",
    "kind": "drill",
    "tee": false,
    "tees": 0,
    "requiresCoach": false
  }
].filter(d=>d.name!=='Basic Tee Work');
