import {configured,watchPortal,watchClock} from './shared.mjs?v=rpbuild33';
import {clockState} from './portal-model.mjs?v=rp127';
import {drills} from './drills.mjs?v=rpbuild16';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let person=null,shared=null,clockId=null,stopClock=null,problem='',offline=true;
function instructions(id){const d=drills.find(x=>x.id===id);return d?[['Purpose',d.primaryPurpose],['Set Up',d.spaceSetup],['Equipment',d.equipment],['How To Do It',d.howItWorks],['Coaching Cues',d.coachingCues],['What Good Looks Like',d.success],['Best Used For',d.bestUsedFor],['Notes',d.notes]].filter(([,v])=>v).map(([k,v])=>'<h4>'+k+'</h4><p>'+esc(v)+'</p>').join(''):'';}
function clockTime(v){if(v===null||v===undefined||v==='')return '';if(typeof v==='number'||/^\d+$/.test(String(v))){const n=Number(v),h=Math.floor(n/60)%24,m=n%60,ap=h>=12?'PM':'AM',hour=h%12||12;return hour+':'+String(m).padStart(2,'0')+' '+ap;}return String(v);}
function timeRange(b){return b.start!==undefined&&b.end!==undefined?esc(clockTime(b.start))+'–'+esc(clockTime(b.end)):'Block '+b.number;}
function coachStation(s){const players=(s.players||[]).filter(Boolean);return '<div class="portal-station"><h3>'+esc(s.duty||s.drill)+'</h3><p><strong>'+timeRange(currentBlock||{})+'</strong>'+(s.resource?' · '+esc(s.resource):'')+'</p>'+(players.length?'<p><strong>Players:</strong> '+players.map(esc).join(' · ')+'</p>':'')+(s.pitcher?'<p><strong>Pitcher:</strong> '+esc(s.pitcher)+'</p>':'')+(s.catcher?'<p><strong>Catcher:</strong> '+esc(s.catcher)+'</p>':'')+(s.equipment?'<p>'+esc(s.equipment)+'</p>':'')+(s.drillId?'<details><summary>What to do / Instructions</summary>'+instructions(s.drillId)+'</details>':'')+'</div>';}
let currentBlock=null;
function coachBlock(b,i,c){currentBlock=b;const isCurrent=i===c.index,next=i===c.index+1,title=isCurrent?'CURRENT ASSIGNMENT':next?'NEXT ASSIGNMENT':'Block '+b.number,body=b.stations.length?b.stations.map(coachStation).join(''):b.coaching?'<div class="portal-station"><h3>Coaching</h3><p><strong>'+timeRange(b)+'</strong></p><p>Circulate between stations, give instruction, watch players, and help where needed.</p></div>':'<p>Not scheduled for this block.</p>';return '<section class="panel '+(isCurrent?'current-block':'')+'"><h2>'+title+'</h2>'+body+'</section>';}
function playerBlock(b,i,c){return '<section class="panel '+(i===c.index?'current-block':'')+'"><h2>Block '+b.number+(i===c.index?' · Current':'')+'</h2>'+b.stations.map(s=>'<div class="portal-station"><h3>'+esc(s.drill)+'</h3><p><strong>'+esc(s.duty)+'</strong> · '+esc(s.resource)+'</p>'+(s.pitcher?'<p>Pitching: '+esc(s.pitcher)+'</p>':'')+(s.catcher?'<p>Catching: '+esc(s.catcher)+'</p>':'')+'<p>'+esc(s.equipment)+'</p>'+(s.drillId?'<details><summary>Details</summary>'+instructions(s.drillId)+'</details>':'')+'</div>').join('')+(b.coaching?'<p>Coaching</p>':'')+(!b.stations.length&&!b.coaching?'<p>Not scheduled for this block.</p>':'')+'</section>';}
function render(){const c=clockState(shared?.clock),app=document.querySelector('#app');if(problem){app.innerHTML='<section class="panel"><h1>Portal unavailable</h1><p>'+esc(problem)+'</p></section>';return;}if(!person){app.innerHTML='<section class="panel"><h1>Loading your portal…</h1></section>';return;}const active=person.active&&c&&!c.done;if(!active){app.innerHTML='<h1>'+esc(person.name)+'</h1><p>'+esc(person.role==='coach'?'Coach Portal':'Player Portal')+'</p>'+(offline?'<p class="notice">Reconnecting. The screen may not show the latest changes.</p>':'')+'<section class="panel"><h2>No active practice</h2><p>Use this same link for your next practice.</p></section>';return;}const clock='<section class="panel" data-clock-key="'+[c.index,c.phase,c.running,c.done,c.started].join('-')+'"><h2>'+esc(person.date)+'</h2><div class="stat-line"><strong>'+(c.started?'Block '+(c.index+1)+' of '+c.blocks:'Ready to start')+'</strong><strong id="portal-time"></strong><strong>'+({work:'Work',rotate:'Rotate',wrap:'Wrap up'}[c.phase])+(c.started&&!c.running?' · Paused':'')+'</strong></div></section>';let blocks;if(person.role==='coach'){const ordered=person.blocks.map((b,i)=>({b,i})),current=ordered.find(x=>x.i===c.index),next=ordered.find(x=>x.i===c.index+1),rest=ordered.filter(x=>x.i!==c.index&&x.i!==c.index+1);blocks=[current,next,...rest].filter(Boolean).map(x=>coachBlock(x.b,x.i,c)).join('');}else blocks=person.blocks.map((b,i)=>playerBlock(b,i,c)).join('');app.innerHTML='<h1>'+esc(person.name)+'</h1><p>'+esc(person.role==='coach'?'Coach Portal':'Player Portal')+'</p>'+(offline?'<p class="notice">Reconnecting. The screen may not show the latest changes.</p>':'')+clock+blocks;tick();}
function tick(){const c=clockState(shared?.clock),el=document.querySelector('#portal-time');if(c?.done&&el){render();return;}if(el){const sec=Math.ceil(c.remaining/1000);el.textContent=String(Math.floor(sec/60)).padStart(2,'0')+':'+String(sec%60).padStart(2,'0');if(document.querySelector('[data-clock-key]')?.getAttribute('data-clock-key')!==[c.index,c.phase,c.running,c.done,c.started].join('-'))render();}}
export async function openPortal(id){document.querySelector('main>header').hidden=false;document.querySelector('#team-name').textContent='Practice With Purpose';document.querySelector('.preview').hidden=true;document.querySelector('main>footer').hidden=true;problem=configured?'':'Shared portals are not connected yet. The RebelsPrep backend still needs setup.';render();if(problem)return;try{await watchPortal(id,async(p,meta)=>{if(!p){problem='This portal link was not found. Ask your coach for the saved link.';render();return;}person=p;offline=meta.fromCache;if(p.clockToken!==clockId){stopClock?.();clockId=p.clockToken;shared=null;if(clockId)try{stopClock=await watchClock(clockId,(value,m)=>{shared=value;offline=m.fromCache;render();},e=>{problem=e.message;render();});}catch(e){problem=e.message;}}render();},e=>{problem=e.message;render();});setInterval(tick,500);}catch(e){problem=e.message;render();}}
