import {configured,watchPortal,watchClock} from './shared.mjs?v=rpbuild18';
import {clockState} from './portal-model.mjs?v=rpbuild18';
import {drills} from './drills.mjs?v=rpbuild16';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let person=null,shared=null,clockId=null,stopClock=null,problem='',offline=true;
function instructions(id){const d=drills.find(x=>x.id===id);return d?[['Purpose',d.primaryPurpose],['Set Up',d.spaceSetup],['Equipment',d.equipment],['How To Do It',d.howItWorks],['Coaching Cues',d.coachingCues],['What Good Looks Like',d.success],['Best Used For',d.bestUsedFor],['Notes',d.notes]].filter(([,v])=>v).map(([k,v])=>'<h4>'+k+'</h4><p>'+esc(v)+'</p>').join(''):'';}
function render(){const c=clockState(shared?.clock),app=document.querySelector('#app');if(problem){app.innerHTML='<section class="panel"><h1>Portal unavailable</h1><p>'+esc(problem)+'</p></section>';return;}if(!person){app.innerHTML='<section class="panel"><h1>Loading your portal…</h1></section>';return;}const active=person.active&&c&&!c.done;app.innerHTML='<h1>'+esc(person.name)+'</h1><p>'+esc(person.role==='coach'?'Coach Portal':'Player Portal')+'</p>'+(offline?'<p class="notice">Reconnecting. The screen may not show the latest changes.</p>':'')+(!active?'<section class="panel"><h2>No active practice</h2><p>Use this same link for your next practice.</p></section>':'<section class="panel" data-clock-key="'+[c.index,c.phase,c.running,c.done,c.started].join('-')+'"><h2>'+esc(person.date)+'</h2><div class="stat-line"><strong>'+(c.started?'Block '+(c.index+1)+' of '+c.blocks:'Ready to start')+'</strong><strong id="portal-time"></strong><strong>'+({work:'Work',rotate:'Rotate',wrap:'Wrap up'}[c.phase])+(c.started&&!c.running?' · Paused':'')+'</strong></div></section>'+person.blocks.map((b,i)=>'<section class="panel '+(i===c.index?'current-block':'')+'"><h2>Block '+b.number+(i===c.index?' · Current':'')+'</h2>'+b.stations.map(s=>'<div class="portal-station"><h3>'+esc(s.drill)+'</h3><p><strong>'+esc(s.duty)+'</strong> · '+esc(s.resource)+'</p>'+(s.pitcher?'<p>Pitching: '+esc(s.pitcher)+'</p>':'')+(s.catcher?'<p>Catching: '+esc(s.catcher)+'</p>':'')+'<p>'+esc(s.equipment)+'</p>'+(s.drillId?'<details><summary>Details</summary>'+instructions(s.drillId)+'</details>':'')+'</div>').join('')+(b.coaching?'<p>Coaching</p>':'')+(!b.stations.length&&!b.coaching?'<p>Not scheduled for this block.</p>':'')+'</section>').join(''));tick();}
function tick(){const c=clockState(shared?.clock),el=document.querySelector('#portal-time');if(c?.done&&el){render();return;}if(el){const sec=Math.ceil(c.remaining/1000);el.textContent=String(Math.floor(sec/60)).padStart(2,'0')+':'+String(sec%60).padStart(2,'0');if(document.querySelector('[data-clock-key]')?.getAttribute('data-clock-key')!==[c.index,c.phase,c.running,c.done,c.started].join('-'))render();}}
export async function openPortal(id){document.querySelector('main>header').hidden=false;document.querySelector('#team-name').textContent='KC Rebels Nationals';document.querySelector('.preview').hidden=true;document.querySelector('main>footer').hidden=true;problem=configured?'':'Shared portals are not connected yet. The RebelsPrep backend still needs setup.';render();if(problem)return;try{await watchPortal(id,async(p,meta)=>{if(!p){problem='This portal link was not found. Ask your coach for the saved link.';render();return;}person=p;offline=meta.fromCache;if(p.clockToken!==clockId){stopClock?.();clockId=p.clockToken;shared=null;if(clockId)try{stopClock=await watchClock(clockId,(value,m)=>{shared=value;offline=m.fromCache;render();},e=>{problem=e.message;render();});}catch(e){problem=e.message;}}render();},e=>{problem=e.message;render();});setInterval(tick,500);}catch(e){problem=e.message;render();}}
